version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
        - ./bin/setup.sql
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_DATABASE=CurrencyConverterDB
        - MYSQL_USER=test
        - MYSQL_PASSWORD=password

    restart: always
    ports:
      - "8083:3306"
  converter:
    volumes:
      - .:/usr/src/converter
    ports:
      - "8082:8082"
    working_dir: /usr/src/converter
    entrypoint:
      - php
      - -S
      - 0.0.0.0:8082
    build: './docker/php'
    stdin_open: true
    tty: true
    depends_on:
      - mysql


